/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colegio2;
import Logica.Pago;
import Logica.PagoBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pagos extends javax.swing.JInternalFrame {

    
    //Array list para mostrar en la segunda tabala de la pura factura
    ArrayList<Pago> Factura = new ArrayList();
    public double Subtotal =0;
      public double Total=0;
      public double Imp=0;
      public double desc=0;
      //instancia  paso 1
    PagoBD BDpago;
    
    
    public Pagos() {
        initComponents();
        BDpago = new PagoBD();
        CargarDatosFacturas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winFactura = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        cboNombre_Alumnos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboDescripcion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        winCobro = new javax.swing.JDialog();
        btnCobrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPaga = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnFactura = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Lista_Facturas = new javax.swing.JTable();

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Cliente", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tblFactura);

        cboNombre_Alumnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNombre_Alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombre_AlumnosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel1.setText("Facturación ");

        jLabel2.setText("Alumnos");

        jLabel3.setText("subtotal ");

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripcion del pago");

        cboDescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Descuento");

        jLabel7.setText("Impuesto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Total a pagar");

        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
        });

        txtImpuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImpuestoKeyReleased(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotal.setText("0");

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winFacturaLayout = new javax.swing.GroupLayout(winFactura.getContentPane());
        winFactura.getContentPane().setLayout(winFacturaLayout);
        winFacturaLayout.setHorizontalGroup(
            winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winFacturaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winFacturaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winFacturaLayout.createSequentialGroup()
                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(winFacturaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, winFacturaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboDescripcion, 0, 97, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboNombre_Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(winFacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(winFacturaLayout.createSequentialGroup()
                                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(txtDescuento)
                                            .addComponent(txtImpuesto)))
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(winFacturaLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnProcesar)))
                        .addGap(27, 27, 27))))
        );
        winFacturaLayout.setVerticalGroup(
            winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winFacturaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNombre_Alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cboDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(29, 29, 29)
                .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(winFacturaLayout.createSequentialGroup()
                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(46, 46, 46)
                .addGroup(winFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotal)
                    .addComponent(btnProcesar))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        btnCobrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Total:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Paga con:");

        txtPaga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagaKeyReleased(evt);
            }
        });

        txtVuelto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Vuelto");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout winCobroLayout = new javax.swing.GroupLayout(winCobro.getContentPane());
        winCobro.getContentPane().setLayout(winCobroLayout);
        winCobroLayout.setHorizontalGroup(
            winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winCobroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winCobroLayout.createSequentialGroup()
                            .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCobrar)
                                .addComponent(jLabel10))
                            .addGap(63, 63, 63))
                        .addGroup(winCobroLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(129, 129, 129)))
                    .addGroup(winCobroLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(122, 122, 122)))
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(btnCancelar)
                    .addComponent(txtPaga, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(txtTotal))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        winCobroLayout.setVerticalGroup(
            winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winCobroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(winCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrar)
                    .addComponent(btnCancelar))
                .addGap(44, 44, 44))
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pagos");

        btnFactura.setText("Nueva factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        btnEditar.setText("jButton1");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFactura)
                    .addComponent(btnEditar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        tbl_Lista_Facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número de factura", "Descripción", "Cliente", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tbl_Lista_Facturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
       CargarCombos();
       winFactura.setSize(700, 450);
       winFactura.setTitle("Nueva Factura");
       txtSubTotal.setText(Integer.toString(0));
       txtDescuento.setText(Integer.toString(0));
       txtImpuesto.setText(Integer.toString(0));
     lblTotal.setText(""+0);
       winFactura.setLocationRelativeTo(tbl_Lista_Facturas);
       winFactura.setVisible(true);
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void cboNombre_AlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombre_AlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNombre_AlumnosActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
   
        CargarTablaFactura();
        Calculos();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
      try{
      double Descuento =0;
      Descuento = Double.parseDouble(txtDescuento.getText());
      
     desc =  Subtotal*(Descuento/100);
     Total=Subtotal-desc+Imp;
      lblTotal.setText(""+Total);
      }catch(Exception e){}
        

// TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void txtImpuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImpuestoKeyReleased
      
         try{
      double Impuesto =0;
      Impuesto = Double.parseDouble(txtImpuesto.getText());
    Imp = Total*(Impuesto/100);
     Total=Total+Imp;
     
      lblTotal.setText(""+Total);
      }catch(Exception e){}// TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoKeyReleased

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
     winCobro.setTitle("Cobro");
      winCobro.setSize(500, 350);
      
       txtTotal.setText(Double.toString(Total));
       txtVuelto.setText("0");
       winCobro.setLocationRelativeTo(tbl_Lista_Facturas);
       winCobro.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtPagaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagaKeyReleased
try {
            
           
            double pagacon= Double.parseDouble(txtPaga.getText());
            double vuelto = pagacon - Total;
            if(vuelto<0){
                txtVuelto.setForeground(Color.red);
            }else {
                txtVuelto.setForeground(Color.black);
            }
            txtVuelto.setText("$"+ vuelto);
        } catch (NumberFormatException e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagaKeyReleased

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        
        Pago p =  new Pago();
        p.setDescripcion(cboDescripcion.getSelectedItem().toString());
        p.setCliente(cboNombre_Alumnos.getSelectedItem().toString());
        p.setMonto(Total);
        BDpago.guardarFactura(p);
        JOptionPane.showMessageDialog(rootPane, "Cargado con exito");
        CargarDatosFacturas();
        winCobro.dispose();
        winFactura.dispose();
        /// la tabal se  pone  en clanco
         DefaultTableModel tableModel =(DefaultTableModel) tblFactura.getModel();
        tableModel.setRowCount(0);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cboDescripcion;
    private javax.swing.JComboBox<String> cboNombre_Alumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblFactura;
    private javax.swing.JTable tbl_Lista_Facturas;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtImpuesto;
    private javax.swing.JTextField txtPaga;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVuelto;
    private javax.swing.JDialog winCobro;
    private javax.swing.JDialog winFactura;
    // End of variables declaration//GEN-END:variables
public void CargarDatosFacturas(){
BDpago.conectarBD();
ResultSet rs= BDpago.buscarFacturas();
tbl_Lista_Facturas.setModel(BDpago.cargarEnTabla(rs));
BDpago.desconectarBD();

}

public void CargarCombos(){
    
    
    cboDescripcion.removeAllItems();
cboDescripcion.addItem(" Seleccione: ");
cboDescripcion.addItem("Matrícula");
cboDescripcion.addItem("Colegiatura");
cboDescripcion.addItem("Otros");

BDpago.conectarBD();
 ResultSet rs = BDpago.seleccionar("select Nombre from alumnos");
       cboNombre_Alumnos.removeAllItems();
        cboNombre_Alumnos.addItem(" Seleccione: ");
        try {
            while (rs.next()) {
                cboNombre_Alumnos.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pagos.class.getName()).log(Level.SEVERE, null, ex);
        }
BDpago.desconectarBD();



}

public void CargarTablaFactura(){

  DefaultTableModel tableModel =(DefaultTableModel) tblFactura.getModel();
        tableModel.setRowCount(0);
        String vector[] = new String[3];
        if(cboDescripcion.getSelectedItem().equals(" Seleccione: ")||cboNombre_Alumnos.getSelectedItem().equals(" Seleccione: "))
        {
            JOptionPane.showMessageDialog(rootPane, "No hay datos a Selecionados", "ERROR", JOptionPane.ERROR_MESSAGE);
       
        } 
   
        else{
            JOptionPane.showMessageDialog(rootPane, "Cargado con exito");
             double precio =0;
            switch(cboDescripcion.getSelectedItem().toString()){
                
                case "Matrícula":
                    precio=70000.0;
                    break;
                case "Colegiatura":
                   precio=90000.0;
                    break;
                case "Otros":
                    precio=50000.0;
             
            }
            Pago p= new Pago();
         
            p.setDescripcion(cboDescripcion.getSelectedItem().toString());
            p.setCliente(cboNombre_Alumnos.getSelectedItem().toString());
            p.setMonto(precio);
            Factura.add(p);
           
             for(int i=0; i<Factura.size();i++){
                      vector[0]=Factura.get(i).getDescripcion();
                      vector[1]=Factura.get(i).getCliente();
                      vector[2]=Double.toString(Factura.get(i).getMonto());
                      tableModel.addRow(vector);
                      tblFactura.setModel(tableModel);
                      tableModel.fireTableDataChanged();
            
             }
            
        }
         
        

}

public void Calculos(){
double totalCantidad = 0;
       
        for (int i = 0; i < tblFactura.getRowCount(); i++) {
            totalCantidad += Double.parseDouble(tblFactura.getValueAt(i, 2).toString());
            
        }
        txtSubTotal.setText(Double.toString(totalCantidad));
        
        Subtotal=totalCantidad;
       lblTotal.setText(""+totalCantidad);
}



    
        
}


